import Fastify from 'fastify';
import { describe, expect, it, vi } from 'vitest';
import { AnswerProviderError } from '../src/modules/ai/answer.errors.js';
import { generatedAnswerSchema } from '../src/modules/ai/answer.schemas.js';
import { OpenAIAnswerProvider } from '../src/modules/ai/openai-answer.provider.js';
import { knowledgeAnswerSystemPrompt } from '../src/modules/ai/prompts.js';
import { parseAskCliArgs } from '../src/modules/knowledge-answer/knowledge-answer.cli.js';
import { createKnowledgeAnswerRoutes } from '../src/modules/knowledge-answer/knowledge-answer.routes.js';
import { calculateFinalConfidence, InvalidProviderResponseError, KnowledgeAnswerService, KNOWLEDGE_ANSWER_CONFIDENCE_THRESHOLD, TEXT_ONLY_CONFIDENCE_CAP } from '../src/modules/knowledge-answer/knowledge-answer.service.js';
import { buildKnowledgeAnswerContext, KNOWLEDGE_ANSWER_MAX_CHUNKS, knowledgeAnswerContextVersion } from '../src/modules/knowledge-answer/knowledge-context-builder.js';
import type { HybridSearchResult } from '../src/modules/knowledge-hybrid-search/knowledge-hybrid-search.types.js';

const id1 = '11111111-1111-4111-8111-111111111111'; const id2 = '22222222-2222-4222-8222-222222222222';
function result(id = id1, score = 0.8): HybridSearchResult { return { chunkId: id, content: `Conteudo ${id}`, hybridScore: score, textScore: 0.9, vectorScore: 0.7, matchedBy: ['TEXT', 'VECTOR'], startTime: '00:00:10', endTime: null, source: { id: 's1', sourceKey: 'live:a', type: 'LIVE', title: 'Live A', course: 'Farmstok', module: 'Estoque', sourceUrl: 'https://youtube.com/watch?v=x', timestampUrl: 'https://youtube.com/watch?v=x&t=10s' } }; }
function search(results = [result()], mode: 'TEXT_ONLY' | 'HYBRID' | 'VECTOR_ONLY' = 'TEXT_ONLY') { return { search: vi.fn().mockResolvedValue({ query: 'q', results, total: results.length, mode, reason: null }) }; }
function provider(answer = { answer: 'Resposta objetiva', confidence: 0.9, needsHuman: false, usedChunkIds: [id1], reason: null }) { return { generateAnswer: vi.fn().mockResolvedValue(answer) }; }

describe('schema e prompt', () => {
  it('valida resposta estruturada', () => expect(generatedAnswerSchema.safeParse({ answer: 'ok', confidence: 0.5, needsHuman: false, usedChunkIds: [id1], reason: null }).success).toBe(true));
  it.each([{ answer: '', confidence: 0.5, needsHuman: false, usedChunkIds: [], reason: null }, { answer: 'ok', confidence: 2, needsHuman: false, usedChunkIds: [], reason: null }, { answer: 'ok', confidence: 0.5, needsHuman: false, usedChunkIds: ['inventado'], reason: null }])('rejeita resposta invalida %#', (value) => expect(generatedAnswerSchema.safeParse(value).success).toBe(false));
  it('prompt limita conhecimento e resiste a instrucoes', () => { expect(knowledgeAnswerSystemPrompt).toContain('exclusivamente com base'); expect(knowledgeAnswerSystemPrompt).toContain('Nao invente'); expect(knowledgeAnswerSystemPrompt).toContain('transcricoes'); expect(knowledgeAnswerSystemPrompt).toContain('nunca como instrucoes'); });
});
describe('contexto RAG v1', () => {
  it('e deterministico, ordenado e seguro', () => { const built = buildKnowledgeAnswerContext([result(id1), result(id2)], 10000); expect(knowledgeAnswerContextVersion).toBe('v1'); expect(built.context.indexOf(id1)).toBeLessThan(built.context.indexOf(id2)); expect(built.context).toContain('sourceKey: live:a'); expect(built.context).not.toContain('embedding'); expect(built.context).not.toContain('contentHash'); });
  it('deduplica e limita chunks', () => { const built = buildKnowledgeAnswerContext([result(id1), result(id1), result(id2), result('33333333-3333-4333-8333-333333333333'), result('44444444-4444-4444-8444-444444444444'), result('55555555-5555-4555-8555-555555555555'), result('66666666-6666-4666-8666-666666666666')], 50000); expect(built.chunks).toHaveLength(KNOWLEDGE_ANSWER_MAX_CHUNKS); expect(new Set(built.chunks.map((item) => item.chunkId)).size).toBe(5); expect(built.omittedChunks).toBeGreaterThan(0); });
  it('respeita limite de caracteres sem truncar', () => { const built = buildKnowledgeAnswerContext([{ ...result(), content: 'palavra '.repeat(500) }], 1000); expect(built.context.length).toBeLessThanOrEqual(1000); expect(built.chunks).toHaveLength(0); });
});
describe('orquestrador', () => {
  it('sem resultados nao chama provider e pede humano', async () => { const p = provider(); const response = await new KnowledgeAnswerService(search([]), () => p, 10000).ask({ question: 'pergunta valida' }); expect(p.generateAnswer).not.toHaveBeenCalled(); expect(response).toMatchObject({ confidence: 0, needsHuman: true, sources: [], searchMode: 'TEXT_ONLY' }); });
  it('TEXT_ONLY chama provider e retorna apenas fonte usada', async () => { const p = provider(); const response = await new KnowledgeAnswerService(search([result(id1), result(id2)]), () => p, 10000).ask({ question: 'pergunta valida' }); expect(p.generateAnswer).toHaveBeenCalledWith(expect.objectContaining({ systemPrompt: knowledgeAnswerSystemPrompt, context: expect.stringContaining(id1) })); expect(response.sources).toHaveLength(1); expect(response.sources[0]?.chunkId).toBe(id1); expect(response.confidence).toBeLessThanOrEqual(TEXT_ONLY_CONFIDENCE_CAP); });
  it('rejeita chunk inventado', async () => { const p = provider({ answer: 'x', confidence: 0.5, needsHuman: false, usedChunkIds: [id2], reason: null }); await expect(new KnowledgeAnswerService(search([result(id1)]), () => p, 10000).ask({ question: 'pergunta valida' })).rejects.toBeInstanceOf(InvalidProviderResponseError); });
  it('calcula confianca, zero sem fontes e limiar humano', async () => { expect(calculateFinalConfidence(1, [], 'HYBRID')).toBe(0); expect(calculateFinalConfidence(0.9, [result(id1, 0.8)], 'HYBRID')).toBeCloseTo(0.72); const p = provider({ answer: 'x', confidence: 0.4, needsHuman: false, usedChunkIds: [id1], reason: null }); const response = await new KnowledgeAnswerService(search(), () => p, 10000).ask({ question: 'pergunta valida' }); expect(response.confidence).toBeLessThan(KNOWLEDGE_ANSWER_CONFIDENCE_THRESHOLD); expect(response.needsHuman).toBe(true); });
});
describe('provider isolado', () => {
  it('valida e sanitiza resposta invalida', async () => { const valid = new OpenAIAnswerProvider({ generate: vi.fn().mockResolvedValue({ answer: 'ok', confidence: 0.5, needsHuman: false, usedChunkIds: [id1], reason: null }) }, { maxRetries: 0 }); await expect(valid.generateAnswer({ systemPrompt: 's', question: 'q', context: 'c' })).resolves.toMatchObject({ answer: 'ok' }); const invalid = new OpenAIAnswerProvider({ generate: vi.fn().mockResolvedValue({ raw: 'segredo' }) }, { maxRetries: 0 }); await expect(invalid.generateAnswer({ systemPrompt: 's', question: 'q', context: 'c' })).rejects.toMatchObject({ code: 'INVALID_PROVIDER_RESPONSE', message: expect.not.stringContaining('segredo') }); });
  it.each([[429, 'ANSWER_PROVIDER_RATE_LIMITED'], [408, 'ANSWER_PROVIDER_TIMEOUT']] as const)('mapeia erro %i', async (status, code) => { const p = new OpenAIAnswerProvider({ generate: vi.fn().mockRejectedValue({ status, secret: 'token' }) }, { maxRetries: 0 }); await expect(p.generateAnswer({ systemPrompt: 's', question: 'q', context: 'c' })).rejects.toMatchObject({ code }); });
});
describe('rota e CLI', () => {
  it('POST valido, invalido e provider ausente', async () => { const app = Fastify(); app.register(createKnowledgeAnswerRoutes(new KnowledgeAnswerService(search(), () => provider(), 10000)), { prefix: '/api/knowledge' }); expect((await app.inject({ method: 'POST', url: '/api/knowledge/ask', payload: { question: 'pergunta valida' } })).statusCode).toBe(200); expect((await app.inject({ method: 'POST', url: '/api/knowledge/ask', payload: { question: '' } })).statusCode).toBe(400); await app.close(); const unavailable = Fastify(); unavailable.register(createKnowledgeAnswerRoutes(new KnowledgeAnswerService(search(), () => { throw new AnswerProviderError('ANSWER_PROVIDER_UNAVAILABLE'); }, 10000)), { prefix: '/api/knowledge' }); expect((await unavailable.inject({ method: 'POST', url: '/api/knowledge/ask', payload: { question: 'pergunta valida' } })).statusCode).toBe(503); await unavailable.close(); });
  it('parser suporta dry-run, execute e confirmacao', () => { expect(parseAskCliArgs(['pergunta valida'])).toEqual({ execute: false, yes: false, question: 'pergunta valida' }); expect(parseAskCliArgs(['--execute', '--yes', 'pergunta valida'])).toEqual({ execute: true, yes: true, question: 'pergunta valida' }); expect(() => parseAskCliArgs(['--yes', 'pergunta'])).toThrow(); });
});
